package controllers

const (
	ERROR_USER_EXIST        = 20002
	ERROR_USER_EXIST_STRING = "用户名已经存在"

	ERROR_USER_NOT_FOUND        = 20003
	ERROR_USER_NOT_FOUND_STRING = "用户名不存在"

	ERROR_USER_PASSWORD_ERROR        = 20004
	ERROR_USER_PASSWORD_ERROR_STRING = "用户密码错误"

	ERROR_USER_SMS_CODE_ERROR        = 200013
	ERROR_USER_SMS_CODE_ERROR_STRING = "短信验证码错误"

	ERROR_USER_SMS_CODE_NOT_FOUND        = 200014
	ERROR_USER_SMS_CODE_NOT_FOUND_STRING = "短信验证码失效或未获取验证码，请重新获取"

	ERROR_USER_NAME_NEED        = 20011
	ERROR_USER_NAME_NEED_STRING = "用户名不能为空"

	ERROR_USER_NAME_PASSWORD_NEED        = 20012
	ERROR_USER_NAME_PASSWORD_NEED_STRING = "用户名和密码不能为空"

	ERROR_USER_SMS_CODE_NEED        = 20013
	ERROR_USER_SMS_CODE_NEED_STRING = "短信验证码不能为空"

	ERROR_WECHAT_CODE_ERROR        = 40001
	ERROR_WECHAT_CODE_ERROR_STRING = "微信用户授权码已失效"

	ERROR_USER_TICKET        = 44001
	ERROR_USER_TICKET_STRING = "尚未登录或者登陆失效，请重新登陆"

	ERROR_DEIVCE_NOT_EXIST        = 30001
	ERROR_DEIVCE_NOT_EXIST_STRING = "设备不存在"

	ERROR_DEIVCE_NOT_BIND        = 30002
	ERROR_DEIVCE_NOT_BIND_STRING = "您没有绑定该设备"

	ERROR_DEIVCE_BINDED        = 30003
	ERROR_DEIVCE_BINDED_STRING = "您已经绑定该设备"
)
